- name: answer_of_everything
  hosts: localhost
  gather_facts: no
  connection: local
  become: true
  tasks:
    - name: "Dependencies"
      pip:
        name: 
          - google-trans-new
          - lxml
        executable: pip3
